SAMPLES : ['sample']

GENOME: "Homo_sapiens_assembly38.fasta"
DBSNP: "Homo_sapiens_assembly38.dbsnp138.vcf"
INDELS: "Homo_sapiens_assembly38.known_indels.vcf"
GOLD_STANDARD: "Mills_and_1000G_gold_standard.indels.hg38.vcf"


CHROMOSOMES: ['chr1', 'chr2','chr3','chr4', 'chr5', 'chr6', 'chr7', 'chr8', 'chr9', 'chr10', 'chr11','chr12', 'chr13', 'chr14', 'chr15', 'chr16', 'chr17', 'chr18', 'chr19', 'chr20' , 'chr21', 'chr22', 'chrX', 'chrY', 'chrM'] 

RG: "A00489_467.HT3G5DMXX.s_2"
ALL_VCF: "all_samples.vcf"
