SAMPLES : ['sample1', 'sample2'] 

GENOME: "Homo_sapiens_assembly38"
DBSNP: "Homo_sapiens_assembly38.dbsnp138.vcf"
INDELS: "Homo_sapiens_assembly38.known_indels.vcf.gz"
GOLD_STANDARD: "Mills_and_1000G_gold_standard.indels.hg38.vcf.gz"
Axiom_Exome: "Axiom_Exome_Plus.genotypes.all_populations.poly.hg38.vcf.gz"
G_phase1: "1000G_phase1.snps.high_confidence.hg38.vcf.gz"
G_omni2: "1000G_omni2.5.hg38.vcf.gz"
hapmap_3: "hapmap_3.3.hg38.vcf.gz"

CHROMOSOMES: ['chrY','chrM']
#['chr1', 'chr2','chr3','chr4', 'chr5', 'chr6', 'chr7', 'chr8', 'chr9', 'chr10', 'chr11','chr12', 'chr13', 'chr14', 'chr15', 'chr16', 'chr17', 'chr18', 'chr19', 'chr20' , 'chr21', 'chr22', 'chrX', 'chrY', 'chrM'] 

RG: "A00489_467.HT3G5DMXX.s_2"
ALL_VCF: "all"

ANNOVAR: /rds/project/yhbl2/rds-yhbl2-genehunter/SM/tools/annovar 
humanDB : /rds/project/yhbl2/rds-yhbl2-genehunter/SM/tools/annovar/humandb
annovar_prefix: "hg38_multianno"
version : hg38

INTERVALS_FILE : 'intervals.list'
GENOMEDB: "my_database"

QD: 2.0
QUAL: 30.0 
SOR: 3.0 
FS: 60.0 
MQ: 40.0
MQRankSum: -12.5
ReadPosRankSum: -8.0 
ExcessHet:  54.69 
